/*
 * Copyright contributors to Hyperledger Besu.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package org.hyperledger.besu.testfuzz.crossvm;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Metadata embedded in corpus entries for cross-VM trace comparison. This structure is stored in
 * the "_crossvm" field of state test JSON files.
 *
 * <p>Example:
 *
 * <pre>{@code
 * {
 *   "_crossvm": {
 *     "traceHash": "abc123def456...",
 *     "stateRoot": "0x...",
 *     "traceLines": 7,
 *     "generatedBy": "geth",
 *     "version": "1.14.0-dev"
 *   }
 * }
 * }</pre>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class CrossVMMetadata {

  @JsonProperty("traceHash")
  private String traceHash;

  @JsonProperty("stateRoot")
  private String stateRoot;

  @JsonProperty("traceLines")
  private int traceLines;

  @JsonProperty("generatedBy")
  private String generatedBy;

  @JsonProperty("version")
  private String version;

  /** Default constructor for Jackson. */
  public CrossVMMetadata() {}

  /**
   * Creates a new CrossVMMetadata.
   *
   * @param traceHash the MD5 hash of normalized trace + stateRoot
   * @param stateRoot the post-execution state root
   * @param traceLines the number of trace lines
   * @param generatedBy the client that generated this (e.g., "geth", "besu")
   * @param version the client version
   */
  public CrossVMMetadata(
      final String traceHash,
      final String stateRoot,
      final int traceLines,
      final String generatedBy,
      final String version) {
    this.traceHash = traceHash;
    this.stateRoot = stateRoot;
    this.traceLines = traceLines;
    this.generatedBy = generatedBy;
    this.version = version;
  }

  /**
   * Gets the trace hash.
   *
   * @return the MD5 hash of normalized trace + stateRoot
   */
  public String getTraceHash() {
    return traceHash;
  }

  /**
   * Gets the state root.
   *
   * @return the post-execution state root
   */
  public String getStateRoot() {
    return stateRoot;
  }

  /**
   * Gets the number of trace lines.
   *
   * @return the trace line count
   */
  public int getTraceLines() {
    return traceLines;
  }

  /**
   * Gets the client that generated this metadata.
   *
   * @return the client name (e.g., "geth", "besu", "nethermind")
   */
  public String getGeneratedBy() {
    return generatedBy;
  }

  /**
   * Gets the client version.
   *
   * @return the version string
   */
  public String getVersion() {
    return version;
  }

  /**
   * Checks if this metadata was generated by a different client.
   *
   * @param thisClient the current client name (e.g., "besu")
   * @return true if generatedBy is set and differs from thisClient
   */
  public boolean isFromOtherClient(final String thisClient) {
    return generatedBy != null && !generatedBy.equalsIgnoreCase(thisClient);
  }

  /**
   * Checks if this metadata has a valid trace hash.
   *
   * @return true if traceHash is non-null and non-empty
   */
  public boolean hasTraceHash() {
    return traceHash != null && !traceHash.isEmpty();
  }

  @Override
  public String toString() {
    return String.format(
        "CrossVMMetadata{generatedBy=%s, version=%s, traceHash=%s, stateRoot=%s, lines=%d}",
        generatedBy,
        version,
        traceHash != null ? traceHash.substring(0, Math.min(8, traceHash.length())) : "null",
        stateRoot != null ? stateRoot.substring(0, Math.min(10, stateRoot.length())) : "null",
        traceLines);
  }
}
