/*
 * Copyright contributors to Hyperledger Besu.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package org.hyperledger.besu.testfuzz.crossvm;

import static org.assertj.core.api.Assertions.assertThat;

import org.hyperledger.besu.testfuzz.StateTestExecutor;
import org.hyperledger.besu.testfuzz.tracing.TracingResult;

import java.io.IOException;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

/**
 * Integration test to validate cross-VM trace comparison with geth corpus. This test loads corpus
 * entries from geth, executes them with Besu, and compares the trace hashes.
 */
class CrossVMValidationTest {

  private static final String GETH_CORPUS_PATH =
      "/home/bhargava/work/github/go-ethereum/tests/fuzzers/statetest/out-2025-12-08";

  private static StateTestExecutor executor;
  private static List<Path> corpusFiles;
  private static boolean corpusExists;

  @BeforeAll
  static void setUp() {
    Path corpusDir = Paths.get(GETH_CORPUS_PATH);
    corpusExists = Files.exists(corpusDir) && Files.isDirectory(corpusDir);

    if (corpusExists) {
      executor = new StateTestExecutor("London");
      corpusFiles = new ArrayList<>();

      try (DirectoryStream<Path> stream = Files.newDirectoryStream(corpusDir, "*.json")) {
        for (Path file : stream) {
          corpusFiles.add(file);
        }
      } catch (IOException e) {
        corpusExists = false;
      }
    }
  }

  @Test
  void validateSingleCorpusEntry() throws IOException {
    if (!corpusExists || corpusFiles.isEmpty()) {
      System.out.println("Skipping test - geth corpus not found at: " + GETH_CORPUS_PATH);
      return;
    }

    // Test first corpus file
    Path firstFile = corpusFiles.get(0);
    byte[] json = Files.readAllBytes(firstFile);

    EnhancedCorpusEntry entry = EnhancedCorpusEntry.parse(json);
    assertThat(entry.hasMetadata()).isTrue();

    CrossVMMetadata metadata = entry.getMetadata();
    System.out.println("Testing file: " + firstFile.getFileName());
    System.out.println("  Generated by: " + metadata.getGeneratedBy());
    System.out.println("  Expected hash: " + metadata.getTraceHash());
    System.out.println("  Expected state root: " + metadata.getStateRoot());
    System.out.println("  Expected trace lines: " + metadata.getTraceLines());

    // Execute with Besu
    byte[] cleanTest = entry.getTestWithoutMetadata();
    TracingResult besuResult = executor.executeWithTracing(cleanTest);

    System.out.println("  Besu hash: " + besuResult.getTraceHash());
    System.out.println("  Besu state root: " + besuResult.getStateRoot());
    System.out.println("  Besu trace lines: " + besuResult.getTraceLines());

    // Compare
    boolean hashMatch = metadata.getTraceHash().equals(besuResult.getTraceHash());
    boolean stateRootMatch = metadata.getStateRoot().equals(besuResult.getStateRoot());
    boolean linecountMatch = metadata.getTraceLines() == besuResult.getTraceLines();

    System.out.println("  Hash match: " + hashMatch);
    System.out.println("  State root match: " + stateRootMatch);
    System.out.println("  Line count match: " + linecountMatch);

    if (!hashMatch) {
      System.out.println("\n  DIVERGENCE DETECTED!");
    }
  }

  @Test
  void validateAllCorpusEntries() throws IOException {
    if (!corpusExists || corpusFiles.isEmpty()) {
      System.out.println("Skipping test - geth corpus not found at: " + GETH_CORPUS_PATH);
      return;
    }

    int total = 0;
    int matches = 0;
    int divergences = 0;
    List<String> divergentFiles = new ArrayList<>();

    for (Path file : corpusFiles) {
      total++;
      try {
        byte[] json = Files.readAllBytes(file);
        EnhancedCorpusEntry entry = EnhancedCorpusEntry.parse(json);

        if (!entry.hasMetadata()) {
          System.out.println("Skipping " + file.getFileName() + " - no metadata");
          continue;
        }

        CrossVMMetadata metadata = entry.getMetadata();
        byte[] cleanTest = entry.getTestWithoutMetadata();
        TracingResult besuResult = executor.executeWithTracing(cleanTest);

        if (metadata.getTraceHash().equals(besuResult.getTraceHash())) {
          matches++;
        } else {
          divergences++;
          divergentFiles.add(file.getFileName().toString());
          System.out.printf(
              "DIVERGENCE: %s - expected=%s actual=%s%n",
              file.getFileName(),
              metadata.getTraceHash().substring(0, 8),
              besuResult.getTraceHash().substring(0, 8));
        }
      } catch (Exception e) {
        System.out.println("Error processing " + file.getFileName() + ": " + e.getMessage());
      }
    }

    System.out.println();
    System.out.println("=== Cross-VM Validation Results ===");
    System.out.println("Total files: " + total);
    System.out.println("Matches: " + matches);
    System.out.println("Divergences: " + divergences);

    if (!divergentFiles.isEmpty()) {
      System.out.println("\nDivergent files:");
      for (String f : divergentFiles) {
        System.out.println("  - " + f);
      }
    }

    // We expect all to match if implementation is correct
    assertThat(divergences)
        .as("All geth corpus entries should match Besu's trace hash")
        .isEqualTo(0);
  }
}
